import SwiftUI

public enum FrostedColor: String, CaseIterable, Identifiable {
    public var id: String { rawValue }

    case background
    case frostedAmber1
    case frostedAmber10
    case frostedAmber11
    case frostedAmber12
    case frostedAmber2
    case frostedAmber3
    case frostedAmber4
    case frostedAmber5
    case frostedAmber6
    case frostedAmber7
    case frostedAmber8
    case frostedAmber9
    case frostedAmber9contrast
    case frostedAmberA1
    case frostedAmberA10
    case frostedAmberA11
    case frostedAmberA12
    case frostedAmberA2
    case frostedAmberA3
    case frostedAmberA4
    case frostedAmberA5
    case frostedAmberA6
    case frostedAmberA7
    case frostedAmberA8
    case frostedAmberA9
    case frostedBlackA1
    case frostedBlackA10
    case frostedBlackA11
    case frostedBlackA12
    case frostedBlackA2
    case frostedBlackA3
    case frostedBlackA4
    case frostedBlackA5
    case frostedBlackA6
    case frostedBlackA7
    case frostedBlackA8
    case frostedBlackA9
    case frostedBlue1
    case frostedBlue10
    case frostedBlue11
    case frostedBlue12
    case frostedBlue2
    case frostedBlue3
    case frostedBlue4
    case frostedBlue5
    case frostedBlue6
    case frostedBlue7
    case frostedBlue8
    case frostedBlue9
    case frostedBlue9contrast
    case frostedBlueA1
    case frostedBlueA10
    case frostedBlueA11
    case frostedBlueA12
    case frostedBlueA2
    case frostedBlueA3
    case frostedBlueA4
    case frostedBlueA5
    case frostedBlueA6
    case frostedBlueA7
    case frostedBlueA8
    case frostedBlueA9
    case frostedBronze1
    case frostedBronze10
    case frostedBronze11
    case frostedBronze12
    case frostedBronze2
    case frostedBronze3
    case frostedBronze4
    case frostedBronze5
    case frostedBronze6
    case frostedBronze7
    case frostedBronze8
    case frostedBronze9
    case frostedBronze9contrast
    case frostedBronzeA1
    case frostedBronzeA10
    case frostedBronzeA11
    case frostedBronzeA12
    case frostedBronzeA2
    case frostedBronzeA3
    case frostedBronzeA4
    case frostedBronzeA5
    case frostedBronzeA6
    case frostedBronzeA7
    case frostedBronzeA8
    case frostedBronzeA9
    case frostedBrown1
    case frostedBrown10
    case frostedBrown11
    case frostedBrown12
    case frostedBrown2
    case frostedBrown3
    case frostedBrown4
    case frostedBrown5
    case frostedBrown6
    case frostedBrown7
    case frostedBrown8
    case frostedBrown9
    case frostedBrown9contrast
    case frostedBrownA1
    case frostedBrownA10
    case frostedBrownA11
    case frostedBrownA12
    case frostedBrownA2
    case frostedBrownA3
    case frostedBrownA4
    case frostedBrownA5
    case frostedBrownA6
    case frostedBrownA7
    case frostedBrownA8
    case frostedBrownA9
    case frostedCrimson1
    case frostedCrimson10
    case frostedCrimson11
    case frostedCrimson12
    case frostedCrimson2
    case frostedCrimson3
    case frostedCrimson4
    case frostedCrimson5
    case frostedCrimson6
    case frostedCrimson7
    case frostedCrimson8
    case frostedCrimson9
    case frostedCrimson9contrast
    case frostedCrimsonA1
    case frostedCrimsonA10
    case frostedCrimsonA11
    case frostedCrimsonA12
    case frostedCrimsonA2
    case frostedCrimsonA3
    case frostedCrimsonA4
    case frostedCrimsonA5
    case frostedCrimsonA6
    case frostedCrimsonA7
    case frostedCrimsonA8
    case frostedCrimsonA9
    case frostedCyan1
    case frostedCyan10
    case frostedCyan11
    case frostedCyan12
    case frostedCyan2
    case frostedCyan3
    case frostedCyan4
    case frostedCyan5
    case frostedCyan6
    case frostedCyan7
    case frostedCyan8
    case frostedCyan9
    case frostedCyan9contrast
    case frostedCyanA1
    case frostedCyanA10
    case frostedCyanA11
    case frostedCyanA12
    case frostedCyanA2
    case frostedCyanA3
    case frostedCyanA4
    case frostedCyanA5
    case frostedCyanA6
    case frostedCyanA7
    case frostedCyanA8
    case frostedCyanA9
    case frostedGold1
    case frostedGold10
    case frostedGold11
    case frostedGold12
    case frostedGold2
    case frostedGold3
    case frostedGold4
    case frostedGold5
    case frostedGold6
    case frostedGold7
    case frostedGold8
    case frostedGold9
    case frostedGold9contrast
    case frostedGoldA1
    case frostedGoldA10
    case frostedGoldA11
    case frostedGoldA12
    case frostedGoldA2
    case frostedGoldA3
    case frostedGoldA4
    case frostedGoldA5
    case frostedGoldA6
    case frostedGoldA7
    case frostedGoldA8
    case frostedGoldA9
    case frostedGrass1
    case frostedGrass10
    case frostedGrass11
    case frostedGrass12
    case frostedGrass2
    case frostedGrass3
    case frostedGrass4
    case frostedGrass5
    case frostedGrass6
    case frostedGrass7
    case frostedGrass8
    case frostedGrass9
    case frostedGrass9contrast
    case frostedGrassA1
    case frostedGrassA10
    case frostedGrassA11
    case frostedGrassA12
    case frostedGrassA2
    case frostedGrassA3
    case frostedGrassA4
    case frostedGrassA5
    case frostedGrassA6
    case frostedGrassA7
    case frostedGrassA8
    case frostedGrassA9
    case frostedGray1
    case frostedGray10
    case frostedGray11
    case frostedGray12
    case frostedGray2
    case frostedGray3
    case frostedGray4
    case frostedGray5
    case frostedGray6
    case frostedGray7
    case frostedGray8
    case frostedGray9
    case frostedGray9contrast
    case frostedGrayA1
    case frostedGrayA10
    case frostedGrayA11
    case frostedGrayA12
    case frostedGrayA2
    case frostedGrayA3
    case frostedGrayA4
    case frostedGrayA5
    case frostedGrayA6
    case frostedGrayA7
    case frostedGrayA8
    case frostedGrayA9
    case frostedGreen1
    case frostedGreen10
    case frostedGreen11
    case frostedGreen12
    case frostedGreen2
    case frostedGreen3
    case frostedGreen4
    case frostedGreen5
    case frostedGreen6
    case frostedGreen7
    case frostedGreen8
    case frostedGreen9
    case frostedGreen9contrast
    case frostedGreenA1
    case frostedGreenA10
    case frostedGreenA11
    case frostedGreenA12
    case frostedGreenA2
    case frostedGreenA3
    case frostedGreenA4
    case frostedGreenA5
    case frostedGreenA6
    case frostedGreenA7
    case frostedGreenA8
    case frostedGreenA9
    case frostedIndigo1
    case frostedIndigo10
    case frostedIndigo11
    case frostedIndigo12
    case frostedIndigo2
    case frostedIndigo3
    case frostedIndigo4
    case frostedIndigo5
    case frostedIndigo6
    case frostedIndigo7
    case frostedIndigo8
    case frostedIndigo9
    case frostedIndigo9contrast
    case frostedIndigoA1
    case frostedIndigoA10
    case frostedIndigoA11
    case frostedIndigoA12
    case frostedIndigoA2
    case frostedIndigoA3
    case frostedIndigoA4
    case frostedIndigoA5
    case frostedIndigoA6
    case frostedIndigoA7
    case frostedIndigoA8
    case frostedIndigoA9
    case frostedIris1
    case frostedIris10
    case frostedIris11
    case frostedIris12
    case frostedIris2
    case frostedIris3
    case frostedIris4
    case frostedIris5
    case frostedIris6
    case frostedIris7
    case frostedIris8
    case frostedIris9
    case frostedIris9contrast
    case frostedIrisA1
    case frostedIrisA10
    case frostedIrisA11
    case frostedIrisA12
    case frostedIrisA2
    case frostedIrisA3
    case frostedIrisA4
    case frostedIrisA5
    case frostedIrisA6
    case frostedIrisA7
    case frostedIrisA8
    case frostedIrisA9
    case frostedJade1
    case frostedJade10
    case frostedJade11
    case frostedJade12
    case frostedJade2
    case frostedJade3
    case frostedJade4
    case frostedJade5
    case frostedJade6
    case frostedJade7
    case frostedJade8
    case frostedJade9
    case frostedJade9contrast
    case frostedJadeA1
    case frostedJadeA10
    case frostedJadeA11
    case frostedJadeA12
    case frostedJadeA2
    case frostedJadeA3
    case frostedJadeA4
    case frostedJadeA5
    case frostedJadeA6
    case frostedJadeA7
    case frostedJadeA8
    case frostedJadeA9
    case frostedLemon1
    case frostedLemon10
    case frostedLemon11
    case frostedLemon12
    case frostedLemon2
    case frostedLemon3
    case frostedLemon4
    case frostedLemon5
    case frostedLemon6
    case frostedLemon7
    case frostedLemon8
    case frostedLemon9
    case frostedLemon9contrast
    case frostedLemonA1
    case frostedLemonA10
    case frostedLemonA11
    case frostedLemonA12
    case frostedLemonA2
    case frostedLemonA3
    case frostedLemonA4
    case frostedLemonA5
    case frostedLemonA6
    case frostedLemonA7
    case frostedLemonA8
    case frostedLemonA9
    case frostedLime1
    case frostedLime10
    case frostedLime11
    case frostedLime12
    case frostedLime2
    case frostedLime3
    case frostedLime4
    case frostedLime5
    case frostedLime6
    case frostedLime7
    case frostedLime8
    case frostedLime9
    case frostedLime9contrast
    case frostedLimeA1
    case frostedLimeA10
    case frostedLimeA11
    case frostedLimeA12
    case frostedLimeA2
    case frostedLimeA3
    case frostedLimeA4
    case frostedLimeA5
    case frostedLimeA6
    case frostedLimeA7
    case frostedLimeA8
    case frostedLimeA9
    case frostedMagenta1
    case frostedMagenta10
    case frostedMagenta11
    case frostedMagenta12
    case frostedMagenta2
    case frostedMagenta3
    case frostedMagenta4
    case frostedMagenta5
    case frostedMagenta6
    case frostedMagenta7
    case frostedMagenta8
    case frostedMagenta9
    case frostedMagenta9contrast
    case frostedMagentaA1
    case frostedMagentaA10
    case frostedMagentaA11
    case frostedMagentaA12
    case frostedMagentaA2
    case frostedMagentaA3
    case frostedMagentaA4
    case frostedMagentaA5
    case frostedMagentaA6
    case frostedMagentaA7
    case frostedMagentaA8
    case frostedMagentaA9
    case frostedMint1
    case frostedMint10
    case frostedMint11
    case frostedMint12
    case frostedMint2
    case frostedMint3
    case frostedMint4
    case frostedMint5
    case frostedMint6
    case frostedMint7
    case frostedMint8
    case frostedMint9
    case frostedMint9contrast
    case frostedMintA1
    case frostedMintA10
    case frostedMintA11
    case frostedMintA12
    case frostedMintA2
    case frostedMintA3
    case frostedMintA4
    case frostedMintA5
    case frostedMintA6
    case frostedMintA7
    case frostedMintA8
    case frostedMintA9
    case frostedOrange1
    case frostedOrange10
    case frostedOrange11
    case frostedOrange12
    case frostedOrange2
    case frostedOrange3
    case frostedOrange4
    case frostedOrange5
    case frostedOrange6
    case frostedOrange7
    case frostedOrange8
    case frostedOrange9
    case frostedOrange9contrast
    case frostedOrangeA1
    case frostedOrangeA10
    case frostedOrangeA11
    case frostedOrangeA12
    case frostedOrangeA2
    case frostedOrangeA3
    case frostedOrangeA4
    case frostedOrangeA5
    case frostedOrangeA6
    case frostedOrangeA7
    case frostedOrangeA8
    case frostedOrangeA9
    case frostedPink1
    case frostedPink10
    case frostedPink11
    case frostedPink12
    case frostedPink2
    case frostedPink3
    case frostedPink4
    case frostedPink5
    case frostedPink6
    case frostedPink7
    case frostedPink8
    case frostedPink9
    case frostedPink9contrast
    case frostedPinkA1
    case frostedPinkA10
    case frostedPinkA11
    case frostedPinkA12
    case frostedPinkA2
    case frostedPinkA3
    case frostedPinkA4
    case frostedPinkA5
    case frostedPinkA6
    case frostedPinkA7
    case frostedPinkA8
    case frostedPinkA9
    case frostedPlum1
    case frostedPlum10
    case frostedPlum11
    case frostedPlum12
    case frostedPlum2
    case frostedPlum3
    case frostedPlum4
    case frostedPlum5
    case frostedPlum6
    case frostedPlum7
    case frostedPlum8
    case frostedPlum9
    case frostedPlum9contrast
    case frostedPlumA1
    case frostedPlumA10
    case frostedPlumA11
    case frostedPlumA12
    case frostedPlumA2
    case frostedPlumA3
    case frostedPlumA4
    case frostedPlumA5
    case frostedPlumA6
    case frostedPlumA7
    case frostedPlumA8
    case frostedPlumA9
    case frostedPurple1
    case frostedPurple10
    case frostedPurple11
    case frostedPurple12
    case frostedPurple2
    case frostedPurple3
    case frostedPurple4
    case frostedPurple5
    case frostedPurple6
    case frostedPurple7
    case frostedPurple8
    case frostedPurple9
    case frostedPurple9contrast
    case frostedPurpleA1
    case frostedPurpleA10
    case frostedPurpleA11
    case frostedPurpleA12
    case frostedPurpleA2
    case frostedPurpleA3
    case frostedPurpleA4
    case frostedPurpleA5
    case frostedPurpleA6
    case frostedPurpleA7
    case frostedPurpleA8
    case frostedPurpleA9
    case frostedRed1
    case frostedRed10
    case frostedRed11
    case frostedRed12
    case frostedRed2
    case frostedRed3
    case frostedRed4
    case frostedRed5
    case frostedRed6
    case frostedRed7
    case frostedRed8
    case frostedRed9
    case frostedRed9contrast
    case frostedRedA1
    case frostedRedA10
    case frostedRedA11
    case frostedRedA12
    case frostedRedA2
    case frostedRedA3
    case frostedRedA4
    case frostedRedA5
    case frostedRedA6
    case frostedRedA7
    case frostedRedA8
    case frostedRedA9
    case frostedRuby1
    case frostedRuby10
    case frostedRuby11
    case frostedRuby12
    case frostedRuby2
    case frostedRuby3
    case frostedRuby4
    case frostedRuby5
    case frostedRuby6
    case frostedRuby7
    case frostedRuby8
    case frostedRuby9
    case frostedRuby9contrast
    case frostedRubyA1
    case frostedRubyA10
    case frostedRubyA11
    case frostedRubyA12
    case frostedRubyA2
    case frostedRubyA3
    case frostedRubyA4
    case frostedRubyA5
    case frostedRubyA6
    case frostedRubyA7
    case frostedRubyA8
    case frostedRubyA9
    case frostedSky1
    case frostedSky10
    case frostedSky11
    case frostedSky12
    case frostedSky2
    case frostedSky3
    case frostedSky4
    case frostedSky5
    case frostedSky6
    case frostedSky7
    case frostedSky8
    case frostedSky9
    case frostedSky9contrast
    case frostedSkyA1
    case frostedSkyA10
    case frostedSkyA11
    case frostedSkyA12
    case frostedSkyA2
    case frostedSkyA3
    case frostedSkyA4
    case frostedSkyA5
    case frostedSkyA6
    case frostedSkyA7
    case frostedSkyA8
    case frostedSkyA9
    case frostedTeal1
    case frostedTeal10
    case frostedTeal11
    case frostedTeal12
    case frostedTeal2
    case frostedTeal3
    case frostedTeal4
    case frostedTeal5
    case frostedTeal6
    case frostedTeal7
    case frostedTeal8
    case frostedTeal9
    case frostedTeal9contrast
    case frostedTealA1
    case frostedTealA10
    case frostedTealA11
    case frostedTealA12
    case frostedTealA2
    case frostedTealA3
    case frostedTealA4
    case frostedTealA5
    case frostedTealA6
    case frostedTealA7
    case frostedTealA8
    case frostedTealA9
    case frostedTomato1
    case frostedTomato10
    case frostedTomato11
    case frostedTomato12
    case frostedTomato2
    case frostedTomato3
    case frostedTomato4
    case frostedTomato5
    case frostedTomato6
    case frostedTomato7
    case frostedTomato8
    case frostedTomato9
    case frostedTomato9contrast
    case frostedTomatoA1
    case frostedTomatoA10
    case frostedTomatoA11
    case frostedTomatoA12
    case frostedTomatoA2
    case frostedTomatoA3
    case frostedTomatoA4
    case frostedTomatoA5
    case frostedTomatoA6
    case frostedTomatoA7
    case frostedTomatoA8
    case frostedTomatoA9
    case frostedViolet1
    case frostedViolet10
    case frostedViolet11
    case frostedViolet12
    case frostedViolet2
    case frostedViolet3
    case frostedViolet4
    case frostedViolet5
    case frostedViolet6
    case frostedViolet7
    case frostedViolet8
    case frostedViolet9
    case frostedViolet9contrast
    case frostedVioletA1
    case frostedVioletA10
    case frostedVioletA11
    case frostedVioletA12
    case frostedVioletA2
    case frostedVioletA3
    case frostedVioletA4
    case frostedVioletA5
    case frostedVioletA6
    case frostedVioletA7
    case frostedVioletA8
    case frostedVioletA9
    case frostedWhiteA1
    case frostedWhiteA10
    case frostedWhiteA11
    case frostedWhiteA12
    case frostedWhiteA2
    case frostedWhiteA3
    case frostedWhiteA4
    case frostedWhiteA5
    case frostedWhiteA6
    case frostedWhiteA7
    case frostedWhiteA8
    case frostedWhiteA9
    case frostedYellow1
    case frostedYellow10
    case frostedYellow11
    case frostedYellow12
    case frostedYellow2
    case frostedYellow3
    case frostedYellow4
    case frostedYellow5
    case frostedYellow6
    case frostedYellow7
    case frostedYellow8
    case frostedYellow9
    case frostedYellow9contrast
    case frostedYellowA1
    case frostedYellowA10
    case frostedYellowA11
    case frostedYellowA12
    case frostedYellowA2
    case frostedYellowA3
    case frostedYellowA4
    case frostedYellowA5
    case frostedYellowA6
    case frostedYellowA7
    case frostedYellowA8
    case frostedYellowA9
    case overlay
    case panelSolid
    case panelTranslucent
    case stroke
    case strokeStrong
    case surface
}

public extension Color {
    init(_ color: FrostedColor) {
        self = Color(color.rawValue, bundle: .module)
    }
}

public extension UIColor {
    /// Fallback to clear color if the color is not found
    convenience init(_ color: FrostedColor, fallbackColor: UIColor = .clear) {
        if UIColor(named: color.rawValue, in: .module, compatibleWith: nil) != nil {
            self.init(named: color.rawValue, in: .module, compatibleWith: nil)!
        } else {
            self.init(cgColor: fallbackColor.cgColor)
        }
    }
}

#Preview {
    ScrollView {
        VStack(alignment: .leading, spacing: 16) {
            ForEach(FrostedColor.allCases) { color in
                HStack(spacing: 8) {
                    Color(color)
                        .frame(width: 20, height: 20)
                        .cornerRadius(4)

                    Text(color.rawValue)

                    Spacer()
                }
            }
        }
        .padding()
    }
}

#Preview {
    ScrollView {
        VStack(alignment: .leading, spacing: 16) {
            ForEach(FrostedColor.allCases) { color in
                HStack(spacing: 8) {
                    Color(color)
                        .frame(width: 20, height: 20)
                        .cornerRadius(4)

                    Text(color.rawValue)

                    Spacer()
                }
            }
        }
        .padding()
    }
    .preferredColorScheme(.dark)
}

public extension FrostedTint {

    static let amber = FrostedTint(
        one: Color(FrostedColor.frostedAmber1),
        two: Color(FrostedColor.frostedAmber2),
        three: Color(FrostedColor.frostedAmber3),
        four: Color(FrostedColor.frostedAmber4),
        five: Color(FrostedColor.frostedAmber5),
        six: Color(FrostedColor.frostedAmber6),
        seven: Color(FrostedColor.frostedAmber7),
        eight: Color(FrostedColor.frostedAmber8),
        nine: Color(FrostedColor.frostedAmber9),
        contrastNine: Color(FrostedColor.frostedAmber9contrast),
        ten: Color(FrostedColor.frostedAmber10),
        eleven: Color(FrostedColor.frostedAmber11),
        twelve: Color(FrostedColor.frostedAmber12),
        A1: Color(FrostedColor.frostedAmberA1),
        A2: Color(FrostedColor.frostedAmberA2),
        A3: Color(FrostedColor.frostedAmberA3),
        A4: Color(FrostedColor.frostedAmberA4),
        A5: Color(FrostedColor.frostedAmberA5),
        A6: Color(FrostedColor.frostedAmberA6),
        A7: Color(FrostedColor.frostedAmberA7),
        A8: Color(FrostedColor.frostedAmberA8),
        A9: Color(FrostedColor.frostedAmberA9),
        A10: Color(FrostedColor.frostedAmberA10),
        A11: Color(FrostedColor.frostedAmberA11),
        A12: Color(FrostedColor.frostedAmberA12)
    )

    static let blue = FrostedTint(
        one: Color(FrostedColor.frostedBlue1),
        two: Color(FrostedColor.frostedBlue2),
        three: Color(FrostedColor.frostedBlue3),
        four: Color(FrostedColor.frostedBlue4),
        five: Color(FrostedColor.frostedBlue5),
        six: Color(FrostedColor.frostedBlue6),
        seven: Color(FrostedColor.frostedBlue7),
        eight: Color(FrostedColor.frostedBlue8),
        nine: Color(FrostedColor.frostedBlue9),
        contrastNine: Color(FrostedColor.frostedBlue9contrast),
        ten: Color(FrostedColor.frostedBlue10),
        eleven: Color(FrostedColor.frostedBlue11),
        twelve: Color(FrostedColor.frostedBlue12),
        A1: Color(FrostedColor.frostedBlueA1),
        A2: Color(FrostedColor.frostedBlueA2),
        A3: Color(FrostedColor.frostedBlueA3),
        A4: Color(FrostedColor.frostedBlueA4),
        A5: Color(FrostedColor.frostedBlueA5),
        A6: Color(FrostedColor.frostedBlueA6),
        A7: Color(FrostedColor.frostedBlueA7),
        A8: Color(FrostedColor.frostedBlueA8),
        A9: Color(FrostedColor.frostedBlueA9),
        A10: Color(FrostedColor.frostedBlueA10),
        A11: Color(FrostedColor.frostedBlueA11),
        A12: Color(FrostedColor.frostedBlueA12)
    )

    static let bronze = FrostedTint(
        one: Color(FrostedColor.frostedBronze1),
        two: Color(FrostedColor.frostedBronze2),
        three: Color(FrostedColor.frostedBronze3),
        four: Color(FrostedColor.frostedBronze4),
        five: Color(FrostedColor.frostedBronze5),
        six: Color(FrostedColor.frostedBronze6),
        seven: Color(FrostedColor.frostedBronze7),
        eight: Color(FrostedColor.frostedBronze8),
        nine: Color(FrostedColor.frostedBronze9),
        contrastNine: Color(FrostedColor.frostedBronze9contrast),
        ten: Color(FrostedColor.frostedBronze10),
        eleven: Color(FrostedColor.frostedBronze11),
        twelve: Color(FrostedColor.frostedBronze12),
        A1: Color(FrostedColor.frostedBronzeA1),
        A2: Color(FrostedColor.frostedBronzeA2),
        A3: Color(FrostedColor.frostedBronzeA3),
        A4: Color(FrostedColor.frostedBronzeA4),
        A5: Color(FrostedColor.frostedBronzeA5),
        A6: Color(FrostedColor.frostedBronzeA6),
        A7: Color(FrostedColor.frostedBronzeA7),
        A8: Color(FrostedColor.frostedBronzeA8),
        A9: Color(FrostedColor.frostedBronzeA9),
        A10: Color(FrostedColor.frostedBronzeA10),
        A11: Color(FrostedColor.frostedBronzeA11),
        A12: Color(FrostedColor.frostedBronzeA12)
    )

    static let brown = FrostedTint(
        one: Color(FrostedColor.frostedBrown1),
        two: Color(FrostedColor.frostedBrown2),
        three: Color(FrostedColor.frostedBrown3),
        four: Color(FrostedColor.frostedBrown4),
        five: Color(FrostedColor.frostedBrown5),
        six: Color(FrostedColor.frostedBrown6),
        seven: Color(FrostedColor.frostedBrown7),
        eight: Color(FrostedColor.frostedBrown8),
        nine: Color(FrostedColor.frostedBrown9),
        contrastNine: Color(FrostedColor.frostedBrown9contrast),
        ten: Color(FrostedColor.frostedBrown10),
        eleven: Color(FrostedColor.frostedBrown11),
        twelve: Color(FrostedColor.frostedBrown12),
        A1: Color(FrostedColor.frostedBrownA1),
        A2: Color(FrostedColor.frostedBrownA2),
        A3: Color(FrostedColor.frostedBrownA3),
        A4: Color(FrostedColor.frostedBrownA4),
        A5: Color(FrostedColor.frostedBrownA5),
        A6: Color(FrostedColor.frostedBrownA6),
        A7: Color(FrostedColor.frostedBrownA7),
        A8: Color(FrostedColor.frostedBrownA8),
        A9: Color(FrostedColor.frostedBrownA9),
        A10: Color(FrostedColor.frostedBrownA10),
        A11: Color(FrostedColor.frostedBrownA11),
        A12: Color(FrostedColor.frostedBrownA12)
    )

    static let crimson = FrostedTint(
        one: Color(FrostedColor.frostedCrimson1),
        two: Color(FrostedColor.frostedCrimson2),
        three: Color(FrostedColor.frostedCrimson3),
        four: Color(FrostedColor.frostedCrimson4),
        five: Color(FrostedColor.frostedCrimson5),
        six: Color(FrostedColor.frostedCrimson6),
        seven: Color(FrostedColor.frostedCrimson7),
        eight: Color(FrostedColor.frostedCrimson8),
        nine: Color(FrostedColor.frostedCrimson9),
        contrastNine: Color(FrostedColor.frostedCrimson9contrast),
        ten: Color(FrostedColor.frostedCrimson10),
        eleven: Color(FrostedColor.frostedCrimson11),
        twelve: Color(FrostedColor.frostedCrimson12),
        A1: Color(FrostedColor.frostedCrimsonA1),
        A2: Color(FrostedColor.frostedCrimsonA2),
        A3: Color(FrostedColor.frostedCrimsonA3),
        A4: Color(FrostedColor.frostedCrimsonA4),
        A5: Color(FrostedColor.frostedCrimsonA5),
        A6: Color(FrostedColor.frostedCrimsonA6),
        A7: Color(FrostedColor.frostedCrimsonA7),
        A8: Color(FrostedColor.frostedCrimsonA8),
        A9: Color(FrostedColor.frostedCrimsonA9),
        A10: Color(FrostedColor.frostedCrimsonA10),
        A11: Color(FrostedColor.frostedCrimsonA11),
        A12: Color(FrostedColor.frostedCrimsonA12)
    )

    static let cyan = FrostedTint(
        one: Color(FrostedColor.frostedCyan1),
        two: Color(FrostedColor.frostedCyan2),
        three: Color(FrostedColor.frostedCyan3),
        four: Color(FrostedColor.frostedCyan4),
        five: Color(FrostedColor.frostedCyan5),
        six: Color(FrostedColor.frostedCyan6),
        seven: Color(FrostedColor.frostedCyan7),
        eight: Color(FrostedColor.frostedCyan8),
        nine: Color(FrostedColor.frostedCyan9),
        contrastNine: Color(FrostedColor.frostedCyan9contrast),
        ten: Color(FrostedColor.frostedCyan10),
        eleven: Color(FrostedColor.frostedCyan11),
        twelve: Color(FrostedColor.frostedCyan12),
        A1: Color(FrostedColor.frostedCyanA1),
        A2: Color(FrostedColor.frostedCyanA2),
        A3: Color(FrostedColor.frostedCyanA3),
        A4: Color(FrostedColor.frostedCyanA4),
        A5: Color(FrostedColor.frostedCyanA5),
        A6: Color(FrostedColor.frostedCyanA6),
        A7: Color(FrostedColor.frostedCyanA7),
        A8: Color(FrostedColor.frostedCyanA8),
        A9: Color(FrostedColor.frostedCyanA9),
        A10: Color(FrostedColor.frostedCyanA10),
        A11: Color(FrostedColor.frostedCyanA11),
        A12: Color(FrostedColor.frostedCyanA12)
    )

    static let gold = FrostedTint(
        one: Color(FrostedColor.frostedGold1),
        two: Color(FrostedColor.frostedGold2),
        three: Color(FrostedColor.frostedGold3),
        four: Color(FrostedColor.frostedGold4),
        five: Color(FrostedColor.frostedGold5),
        six: Color(FrostedColor.frostedGold6),
        seven: Color(FrostedColor.frostedGold7),
        eight: Color(FrostedColor.frostedGold8),
        nine: Color(FrostedColor.frostedGold9),
        contrastNine: Color(FrostedColor.frostedGold9contrast),
        ten: Color(FrostedColor.frostedGold10),
        eleven: Color(FrostedColor.frostedGold11),
        twelve: Color(FrostedColor.frostedGold12),
        A1: Color(FrostedColor.frostedGoldA1),
        A2: Color(FrostedColor.frostedGoldA2),
        A3: Color(FrostedColor.frostedGoldA3),
        A4: Color(FrostedColor.frostedGoldA4),
        A5: Color(FrostedColor.frostedGoldA5),
        A6: Color(FrostedColor.frostedGoldA6),
        A7: Color(FrostedColor.frostedGoldA7),
        A8: Color(FrostedColor.frostedGoldA8),
        A9: Color(FrostedColor.frostedGoldA9),
        A10: Color(FrostedColor.frostedGoldA10),
        A11: Color(FrostedColor.frostedGoldA11),
        A12: Color(FrostedColor.frostedGoldA12)
    )

    static let grass = FrostedTint(
        one: Color(FrostedColor.frostedGrass1),
        two: Color(FrostedColor.frostedGrass2),
        three: Color(FrostedColor.frostedGrass3),
        four: Color(FrostedColor.frostedGrass4),
        five: Color(FrostedColor.frostedGrass5),
        six: Color(FrostedColor.frostedGrass6),
        seven: Color(FrostedColor.frostedGrass7),
        eight: Color(FrostedColor.frostedGrass8),
        nine: Color(FrostedColor.frostedGrass9),
        contrastNine: Color(FrostedColor.frostedGrass9contrast),
        ten: Color(FrostedColor.frostedGrass10),
        eleven: Color(FrostedColor.frostedGrass11),
        twelve: Color(FrostedColor.frostedGrass12),
        A1: Color(FrostedColor.frostedGrassA1),
        A2: Color(FrostedColor.frostedGrassA2),
        A3: Color(FrostedColor.frostedGrassA3),
        A4: Color(FrostedColor.frostedGrassA4),
        A5: Color(FrostedColor.frostedGrassA5),
        A6: Color(FrostedColor.frostedGrassA6),
        A7: Color(FrostedColor.frostedGrassA7),
        A8: Color(FrostedColor.frostedGrassA8),
        A9: Color(FrostedColor.frostedGrassA9),
        A10: Color(FrostedColor.frostedGrassA10),
        A11: Color(FrostedColor.frostedGrassA11),
        A12: Color(FrostedColor.frostedGrassA12)
    )

    static let gray = FrostedTint(
        one: Color(FrostedColor.frostedGray1),
        two: Color(FrostedColor.frostedGray2),
        three: Color(FrostedColor.frostedGray3),
        four: Color(FrostedColor.frostedGray4),
        five: Color(FrostedColor.frostedGray5),
        six: Color(FrostedColor.frostedGray6),
        seven: Color(FrostedColor.frostedGray7),
        eight: Color(FrostedColor.frostedGray8),
        nine: Color(FrostedColor.frostedGray9),
        contrastNine: Color(FrostedColor.frostedGray9contrast),
        ten: Color(FrostedColor.frostedGray10),
        eleven: Color(FrostedColor.frostedGray11),
        twelve: Color(FrostedColor.frostedGray12),
        A1: Color(FrostedColor.frostedGrayA1),
        A2: Color(FrostedColor.frostedGrayA2),
        A3: Color(FrostedColor.frostedGrayA3),
        A4: Color(FrostedColor.frostedGrayA4),
        A5: Color(FrostedColor.frostedGrayA5),
        A6: Color(FrostedColor.frostedGrayA6),
        A7: Color(FrostedColor.frostedGrayA7),
        A8: Color(FrostedColor.frostedGrayA8),
        A9: Color(FrostedColor.frostedGrayA9),
        A10: Color(FrostedColor.frostedGrayA10),
        A11: Color(FrostedColor.frostedGrayA11),
        A12: Color(FrostedColor.frostedGrayA12)
    )

    static let green = FrostedTint(
        one: Color(FrostedColor.frostedGreen1),
        two: Color(FrostedColor.frostedGreen2),
        three: Color(FrostedColor.frostedGreen3),
        four: Color(FrostedColor.frostedGreen4),
        five: Color(FrostedColor.frostedGreen5),
        six: Color(FrostedColor.frostedGreen6),
        seven: Color(FrostedColor.frostedGreen7),
        eight: Color(FrostedColor.frostedGreen8),
        nine: Color(FrostedColor.frostedGreen9),
        contrastNine: Color(FrostedColor.frostedGreen9contrast),
        ten: Color(FrostedColor.frostedGreen10),
        eleven: Color(FrostedColor.frostedGreen11),
        twelve: Color(FrostedColor.frostedGreen12),
        A1: Color(FrostedColor.frostedGreenA1),
        A2: Color(FrostedColor.frostedGreenA2),
        A3: Color(FrostedColor.frostedGreenA3),
        A4: Color(FrostedColor.frostedGreenA4),
        A5: Color(FrostedColor.frostedGreenA5),
        A6: Color(FrostedColor.frostedGreenA6),
        A7: Color(FrostedColor.frostedGreenA7),
        A8: Color(FrostedColor.frostedGreenA8),
        A9: Color(FrostedColor.frostedGreenA9),
        A10: Color(FrostedColor.frostedGreenA10),
        A11: Color(FrostedColor.frostedGreenA11),
        A12: Color(FrostedColor.frostedGreenA12)
    )

    static let indigo = FrostedTint(
        one: Color(FrostedColor.frostedIndigo1),
        two: Color(FrostedColor.frostedIndigo2),
        three: Color(FrostedColor.frostedIndigo3),
        four: Color(FrostedColor.frostedIndigo4),
        five: Color(FrostedColor.frostedIndigo5),
        six: Color(FrostedColor.frostedIndigo6),
        seven: Color(FrostedColor.frostedIndigo7),
        eight: Color(FrostedColor.frostedIndigo8),
        nine: Color(FrostedColor.frostedIndigo9),
        contrastNine: Color(FrostedColor.frostedIndigo9contrast),
        ten: Color(FrostedColor.frostedIndigo10),
        eleven: Color(FrostedColor.frostedIndigo11),
        twelve: Color(FrostedColor.frostedIndigo12),
        A1: Color(FrostedColor.frostedIndigoA1),
        A2: Color(FrostedColor.frostedIndigoA2),
        A3: Color(FrostedColor.frostedIndigoA3),
        A4: Color(FrostedColor.frostedIndigoA4),
        A5: Color(FrostedColor.frostedIndigoA5),
        A6: Color(FrostedColor.frostedIndigoA6),
        A7: Color(FrostedColor.frostedIndigoA7),
        A8: Color(FrostedColor.frostedIndigoA8),
        A9: Color(FrostedColor.frostedIndigoA9),
        A10: Color(FrostedColor.frostedIndigoA10),
        A11: Color(FrostedColor.frostedIndigoA11),
        A12: Color(FrostedColor.frostedIndigoA12)
    )

    static let iris = FrostedTint(
        one: Color(FrostedColor.frostedIris1),
        two: Color(FrostedColor.frostedIris2),
        three: Color(FrostedColor.frostedIris3),
        four: Color(FrostedColor.frostedIris4),
        five: Color(FrostedColor.frostedIris5),
        six: Color(FrostedColor.frostedIris6),
        seven: Color(FrostedColor.frostedIris7),
        eight: Color(FrostedColor.frostedIris8),
        nine: Color(FrostedColor.frostedIris9),
        contrastNine: Color(FrostedColor.frostedIris9contrast),
        ten: Color(FrostedColor.frostedIris10),
        eleven: Color(FrostedColor.frostedIris11),
        twelve: Color(FrostedColor.frostedIris12),
        A1: Color(FrostedColor.frostedIrisA1),
        A2: Color(FrostedColor.frostedIrisA2),
        A3: Color(FrostedColor.frostedIrisA3),
        A4: Color(FrostedColor.frostedIrisA4),
        A5: Color(FrostedColor.frostedIrisA5),
        A6: Color(FrostedColor.frostedIrisA6),
        A7: Color(FrostedColor.frostedIrisA7),
        A8: Color(FrostedColor.frostedIrisA8),
        A9: Color(FrostedColor.frostedIrisA9),
        A10: Color(FrostedColor.frostedIrisA10),
        A11: Color(FrostedColor.frostedIrisA11),
        A12: Color(FrostedColor.frostedIrisA12)
    )

    static let jade = FrostedTint(
        one: Color(FrostedColor.frostedJade1),
        two: Color(FrostedColor.frostedJade2),
        three: Color(FrostedColor.frostedJade3),
        four: Color(FrostedColor.frostedJade4),
        five: Color(FrostedColor.frostedJade5),
        six: Color(FrostedColor.frostedJade6),
        seven: Color(FrostedColor.frostedJade7),
        eight: Color(FrostedColor.frostedJade8),
        nine: Color(FrostedColor.frostedJade9),
        contrastNine: Color(FrostedColor.frostedJade9contrast),
        ten: Color(FrostedColor.frostedJade10),
        eleven: Color(FrostedColor.frostedJade11),
        twelve: Color(FrostedColor.frostedJade12),
        A1: Color(FrostedColor.frostedJadeA1),
        A2: Color(FrostedColor.frostedJadeA2),
        A3: Color(FrostedColor.frostedJadeA3),
        A4: Color(FrostedColor.frostedJadeA4),
        A5: Color(FrostedColor.frostedJadeA5),
        A6: Color(FrostedColor.frostedJadeA6),
        A7: Color(FrostedColor.frostedJadeA7),
        A8: Color(FrostedColor.frostedJadeA8),
        A9: Color(FrostedColor.frostedJadeA9),
        A10: Color(FrostedColor.frostedJadeA10),
        A11: Color(FrostedColor.frostedJadeA11),
        A12: Color(FrostedColor.frostedJadeA12)
    )

    static let lemon = FrostedTint(
        one: Color(FrostedColor.frostedLemon1),
        two: Color(FrostedColor.frostedLemon2),
        three: Color(FrostedColor.frostedLemon3),
        four: Color(FrostedColor.frostedLemon4),
        five: Color(FrostedColor.frostedLemon5),
        six: Color(FrostedColor.frostedLemon6),
        seven: Color(FrostedColor.frostedLemon7),
        eight: Color(FrostedColor.frostedLemon8),
        nine: Color(FrostedColor.frostedLemon9),
        contrastNine: Color(FrostedColor.frostedLemon9contrast),
        ten: Color(FrostedColor.frostedLemon10),
        eleven: Color(FrostedColor.frostedLemon11),
        twelve: Color(FrostedColor.frostedLemon12),
        A1: Color(FrostedColor.frostedLemonA1),
        A2: Color(FrostedColor.frostedLemonA2),
        A3: Color(FrostedColor.frostedLemonA3),
        A4: Color(FrostedColor.frostedLemonA4),
        A5: Color(FrostedColor.frostedLemonA5),
        A6: Color(FrostedColor.frostedLemonA6),
        A7: Color(FrostedColor.frostedLemonA7),
        A8: Color(FrostedColor.frostedLemonA8),
        A9: Color(FrostedColor.frostedLemonA9),
        A10: Color(FrostedColor.frostedLemonA10),
        A11: Color(FrostedColor.frostedLemonA11),
        A12: Color(FrostedColor.frostedLemonA12)
    )

    static let lime = FrostedTint(
        one: Color(FrostedColor.frostedLime1),
        two: Color(FrostedColor.frostedLime2),
        three: Color(FrostedColor.frostedLime3),
        four: Color(FrostedColor.frostedLime4),
        five: Color(FrostedColor.frostedLime5),
        six: Color(FrostedColor.frostedLime6),
        seven: Color(FrostedColor.frostedLime7),
        eight: Color(FrostedColor.frostedLime8),
        nine: Color(FrostedColor.frostedLime9),
        contrastNine: Color(FrostedColor.frostedLime9contrast),
        ten: Color(FrostedColor.frostedLime10),
        eleven: Color(FrostedColor.frostedLime11),
        twelve: Color(FrostedColor.frostedLime12),
        A1: Color(FrostedColor.frostedLimeA1),
        A2: Color(FrostedColor.frostedLimeA2),
        A3: Color(FrostedColor.frostedLimeA3),
        A4: Color(FrostedColor.frostedLimeA4),
        A5: Color(FrostedColor.frostedLimeA5),
        A6: Color(FrostedColor.frostedLimeA6),
        A7: Color(FrostedColor.frostedLimeA7),
        A8: Color(FrostedColor.frostedLimeA8),
        A9: Color(FrostedColor.frostedLimeA9),
        A10: Color(FrostedColor.frostedLimeA10),
        A11: Color(FrostedColor.frostedLimeA11),
        A12: Color(FrostedColor.frostedLimeA12)
    )

    static let magenta = FrostedTint(
        one: Color(FrostedColor.frostedMagenta1),
        two: Color(FrostedColor.frostedMagenta2),
        three: Color(FrostedColor.frostedMagenta3),
        four: Color(FrostedColor.frostedMagenta4),
        five: Color(FrostedColor.frostedMagenta5),
        six: Color(FrostedColor.frostedMagenta6),
        seven: Color(FrostedColor.frostedMagenta7),
        eight: Color(FrostedColor.frostedMagenta8),
        nine: Color(FrostedColor.frostedMagenta9),
        contrastNine: Color(FrostedColor.frostedMagenta9contrast),
        ten: Color(FrostedColor.frostedMagenta10),
        eleven: Color(FrostedColor.frostedMagenta11),
        twelve: Color(FrostedColor.frostedMagenta12),
        A1: Color(FrostedColor.frostedMagentaA1),
        A2: Color(FrostedColor.frostedMagentaA2),
        A3: Color(FrostedColor.frostedMagentaA3),
        A4: Color(FrostedColor.frostedMagentaA4),
        A5: Color(FrostedColor.frostedMagentaA5),
        A6: Color(FrostedColor.frostedMagentaA6),
        A7: Color(FrostedColor.frostedMagentaA7),
        A8: Color(FrostedColor.frostedMagentaA8),
        A9: Color(FrostedColor.frostedMagentaA9),
        A10: Color(FrostedColor.frostedMagentaA10),
        A11: Color(FrostedColor.frostedMagentaA11),
        A12: Color(FrostedColor.frostedMagentaA12)
    )

    static let mint = FrostedTint(
        one: Color(FrostedColor.frostedMint1),
        two: Color(FrostedColor.frostedMint2),
        three: Color(FrostedColor.frostedMint3),
        four: Color(FrostedColor.frostedMint4),
        five: Color(FrostedColor.frostedMint5),
        six: Color(FrostedColor.frostedMint6),
        seven: Color(FrostedColor.frostedMint7),
        eight: Color(FrostedColor.frostedMint8),
        nine: Color(FrostedColor.frostedMint9),
        contrastNine: Color(FrostedColor.frostedMint9contrast),
        ten: Color(FrostedColor.frostedMint10),
        eleven: Color(FrostedColor.frostedMint11),
        twelve: Color(FrostedColor.frostedMint12),
        A1: Color(FrostedColor.frostedMintA1),
        A2: Color(FrostedColor.frostedMintA2),
        A3: Color(FrostedColor.frostedMintA3),
        A4: Color(FrostedColor.frostedMintA4),
        A5: Color(FrostedColor.frostedMintA5),
        A6: Color(FrostedColor.frostedMintA6),
        A7: Color(FrostedColor.frostedMintA7),
        A8: Color(FrostedColor.frostedMintA8),
        A9: Color(FrostedColor.frostedMintA9),
        A10: Color(FrostedColor.frostedMintA10),
        A11: Color(FrostedColor.frostedMintA11),
        A12: Color(FrostedColor.frostedMintA12)
    )

    static let orange = FrostedTint(
        one: Color(FrostedColor.frostedOrange1),
        two: Color(FrostedColor.frostedOrange2),
        three: Color(FrostedColor.frostedOrange3),
        four: Color(FrostedColor.frostedOrange4),
        five: Color(FrostedColor.frostedOrange5),
        six: Color(FrostedColor.frostedOrange6),
        seven: Color(FrostedColor.frostedOrange7),
        eight: Color(FrostedColor.frostedOrange8),
        nine: Color(FrostedColor.frostedOrange9),
        contrastNine: Color(FrostedColor.frostedOrange9contrast),
        ten: Color(FrostedColor.frostedOrange10),
        eleven: Color(FrostedColor.frostedOrange11),
        twelve: Color(FrostedColor.frostedOrange12),
        A1: Color(FrostedColor.frostedOrangeA1),
        A2: Color(FrostedColor.frostedOrangeA2),
        A3: Color(FrostedColor.frostedOrangeA3),
        A4: Color(FrostedColor.frostedOrangeA4),
        A5: Color(FrostedColor.frostedOrangeA5),
        A6: Color(FrostedColor.frostedOrangeA6),
        A7: Color(FrostedColor.frostedOrangeA7),
        A8: Color(FrostedColor.frostedOrangeA8),
        A9: Color(FrostedColor.frostedOrangeA9),
        A10: Color(FrostedColor.frostedOrangeA10),
        A11: Color(FrostedColor.frostedOrangeA11),
        A12: Color(FrostedColor.frostedOrangeA12)
    )

    static let pink = FrostedTint(
        one: Color(FrostedColor.frostedPink1),
        two: Color(FrostedColor.frostedPink2),
        three: Color(FrostedColor.frostedPink3),
        four: Color(FrostedColor.frostedPink4),
        five: Color(FrostedColor.frostedPink5),
        six: Color(FrostedColor.frostedPink6),
        seven: Color(FrostedColor.frostedPink7),
        eight: Color(FrostedColor.frostedPink8),
        nine: Color(FrostedColor.frostedPink9),
        contrastNine: Color(FrostedColor.frostedPink9contrast),
        ten: Color(FrostedColor.frostedPink10),
        eleven: Color(FrostedColor.frostedPink11),
        twelve: Color(FrostedColor.frostedPink12),
        A1: Color(FrostedColor.frostedPinkA1),
        A2: Color(FrostedColor.frostedPinkA2),
        A3: Color(FrostedColor.frostedPinkA3),
        A4: Color(FrostedColor.frostedPinkA4),
        A5: Color(FrostedColor.frostedPinkA5),
        A6: Color(FrostedColor.frostedPinkA6),
        A7: Color(FrostedColor.frostedPinkA7),
        A8: Color(FrostedColor.frostedPinkA8),
        A9: Color(FrostedColor.frostedPinkA9),
        A10: Color(FrostedColor.frostedPinkA10),
        A11: Color(FrostedColor.frostedPinkA11),
        A12: Color(FrostedColor.frostedPinkA12)
    )

    static let plum = FrostedTint(
        one: Color(FrostedColor.frostedPlum1),
        two: Color(FrostedColor.frostedPlum2),
        three: Color(FrostedColor.frostedPlum3),
        four: Color(FrostedColor.frostedPlum4),
        five: Color(FrostedColor.frostedPlum5),
        six: Color(FrostedColor.frostedPlum6),
        seven: Color(FrostedColor.frostedPlum7),
        eight: Color(FrostedColor.frostedPlum8),
        nine: Color(FrostedColor.frostedPlum9),
        contrastNine: Color(FrostedColor.frostedPlum9contrast),
        ten: Color(FrostedColor.frostedPlum10),
        eleven: Color(FrostedColor.frostedPlum11),
        twelve: Color(FrostedColor.frostedPlum12),
        A1: Color(FrostedColor.frostedPlumA1),
        A2: Color(FrostedColor.frostedPlumA2),
        A3: Color(FrostedColor.frostedPlumA3),
        A4: Color(FrostedColor.frostedPlumA4),
        A5: Color(FrostedColor.frostedPlumA5),
        A6: Color(FrostedColor.frostedPlumA6),
        A7: Color(FrostedColor.frostedPlumA7),
        A8: Color(FrostedColor.frostedPlumA8),
        A9: Color(FrostedColor.frostedPlumA9),
        A10: Color(FrostedColor.frostedPlumA10),
        A11: Color(FrostedColor.frostedPlumA11),
        A12: Color(FrostedColor.frostedPlumA12)
    )

    static let purple = FrostedTint(
        one: Color(FrostedColor.frostedPurple1),
        two: Color(FrostedColor.frostedPurple2),
        three: Color(FrostedColor.frostedPurple3),
        four: Color(FrostedColor.frostedPurple4),
        five: Color(FrostedColor.frostedPurple5),
        six: Color(FrostedColor.frostedPurple6),
        seven: Color(FrostedColor.frostedPurple7),
        eight: Color(FrostedColor.frostedPurple8),
        nine: Color(FrostedColor.frostedPurple9),
        contrastNine: Color(FrostedColor.frostedPurple9contrast),
        ten: Color(FrostedColor.frostedPurple10),
        eleven: Color(FrostedColor.frostedPurple11),
        twelve: Color(FrostedColor.frostedPurple12),
        A1: Color(FrostedColor.frostedPurpleA1),
        A2: Color(FrostedColor.frostedPurpleA2),
        A3: Color(FrostedColor.frostedPurpleA3),
        A4: Color(FrostedColor.frostedPurpleA4),
        A5: Color(FrostedColor.frostedPurpleA5),
        A6: Color(FrostedColor.frostedPurpleA6),
        A7: Color(FrostedColor.frostedPurpleA7),
        A8: Color(FrostedColor.frostedPurpleA8),
        A9: Color(FrostedColor.frostedPurpleA9),
        A10: Color(FrostedColor.frostedPurpleA10),
        A11: Color(FrostedColor.frostedPurpleA11),
        A12: Color(FrostedColor.frostedPurpleA12)
    )

    static let red = FrostedTint(
        one: Color(FrostedColor.frostedRed1),
        two: Color(FrostedColor.frostedRed2),
        three: Color(FrostedColor.frostedRed3),
        four: Color(FrostedColor.frostedRed4),
        five: Color(FrostedColor.frostedRed5),
        six: Color(FrostedColor.frostedRed6),
        seven: Color(FrostedColor.frostedRed7),
        eight: Color(FrostedColor.frostedRed8),
        nine: Color(FrostedColor.frostedRed9),
        contrastNine: Color(FrostedColor.frostedRed9contrast),
        ten: Color(FrostedColor.frostedRed10),
        eleven: Color(FrostedColor.frostedRed11),
        twelve: Color(FrostedColor.frostedRed12),
        A1: Color(FrostedColor.frostedRedA1),
        A2: Color(FrostedColor.frostedRedA2),
        A3: Color(FrostedColor.frostedRedA3),
        A4: Color(FrostedColor.frostedRedA4),
        A5: Color(FrostedColor.frostedRedA5),
        A6: Color(FrostedColor.frostedRedA6),
        A7: Color(FrostedColor.frostedRedA7),
        A8: Color(FrostedColor.frostedRedA8),
        A9: Color(FrostedColor.frostedRedA9),
        A10: Color(FrostedColor.frostedRedA10),
        A11: Color(FrostedColor.frostedRedA11),
        A12: Color(FrostedColor.frostedRedA12)
    )

    static let ruby = FrostedTint(
        one: Color(FrostedColor.frostedRuby1),
        two: Color(FrostedColor.frostedRuby2),
        three: Color(FrostedColor.frostedRuby3),
        four: Color(FrostedColor.frostedRuby4),
        five: Color(FrostedColor.frostedRuby5),
        six: Color(FrostedColor.frostedRuby6),
        seven: Color(FrostedColor.frostedRuby7),
        eight: Color(FrostedColor.frostedRuby8),
        nine: Color(FrostedColor.frostedRuby9),
        contrastNine: Color(FrostedColor.frostedRuby9contrast),
        ten: Color(FrostedColor.frostedRuby10),
        eleven: Color(FrostedColor.frostedRuby11),
        twelve: Color(FrostedColor.frostedRuby12),
        A1: Color(FrostedColor.frostedRubyA1),
        A2: Color(FrostedColor.frostedRubyA2),
        A3: Color(FrostedColor.frostedRubyA3),
        A4: Color(FrostedColor.frostedRubyA4),
        A5: Color(FrostedColor.frostedRubyA5),
        A6: Color(FrostedColor.frostedRubyA6),
        A7: Color(FrostedColor.frostedRubyA7),
        A8: Color(FrostedColor.frostedRubyA8),
        A9: Color(FrostedColor.frostedRubyA9),
        A10: Color(FrostedColor.frostedRubyA10),
        A11: Color(FrostedColor.frostedRubyA11),
        A12: Color(FrostedColor.frostedRubyA12)
    )

    static let sky = FrostedTint(
        one: Color(FrostedColor.frostedSky1),
        two: Color(FrostedColor.frostedSky2),
        three: Color(FrostedColor.frostedSky3),
        four: Color(FrostedColor.frostedSky4),
        five: Color(FrostedColor.frostedSky5),
        six: Color(FrostedColor.frostedSky6),
        seven: Color(FrostedColor.frostedSky7),
        eight: Color(FrostedColor.frostedSky8),
        nine: Color(FrostedColor.frostedSky9),
        contrastNine: Color(FrostedColor.frostedSky9contrast),
        ten: Color(FrostedColor.frostedSky10),
        eleven: Color(FrostedColor.frostedSky11),
        twelve: Color(FrostedColor.frostedSky12),
        A1: Color(FrostedColor.frostedSkyA1),
        A2: Color(FrostedColor.frostedSkyA2),
        A3: Color(FrostedColor.frostedSkyA3),
        A4: Color(FrostedColor.frostedSkyA4),
        A5: Color(FrostedColor.frostedSkyA5),
        A6: Color(FrostedColor.frostedSkyA6),
        A7: Color(FrostedColor.frostedSkyA7),
        A8: Color(FrostedColor.frostedSkyA8),
        A9: Color(FrostedColor.frostedSkyA9),
        A10: Color(FrostedColor.frostedSkyA10),
        A11: Color(FrostedColor.frostedSkyA11),
        A12: Color(FrostedColor.frostedSkyA12)
    )

    static let teal = FrostedTint(
        one: Color(FrostedColor.frostedTeal1),
        two: Color(FrostedColor.frostedTeal2),
        three: Color(FrostedColor.frostedTeal3),
        four: Color(FrostedColor.frostedTeal4),
        five: Color(FrostedColor.frostedTeal5),
        six: Color(FrostedColor.frostedTeal6),
        seven: Color(FrostedColor.frostedTeal7),
        eight: Color(FrostedColor.frostedTeal8),
        nine: Color(FrostedColor.frostedTeal9),
        contrastNine: Color(FrostedColor.frostedTeal9contrast),
        ten: Color(FrostedColor.frostedTeal10),
        eleven: Color(FrostedColor.frostedTeal11),
        twelve: Color(FrostedColor.frostedTeal12),
        A1: Color(FrostedColor.frostedTealA1),
        A2: Color(FrostedColor.frostedTealA2),
        A3: Color(FrostedColor.frostedTealA3),
        A4: Color(FrostedColor.frostedTealA4),
        A5: Color(FrostedColor.frostedTealA5),
        A6: Color(FrostedColor.frostedTealA6),
        A7: Color(FrostedColor.frostedTealA7),
        A8: Color(FrostedColor.frostedTealA8),
        A9: Color(FrostedColor.frostedTealA9),
        A10: Color(FrostedColor.frostedTealA10),
        A11: Color(FrostedColor.frostedTealA11),
        A12: Color(FrostedColor.frostedTealA12)
    )

    static let tomato = FrostedTint(
        one: Color(FrostedColor.frostedTomato1),
        two: Color(FrostedColor.frostedTomato2),
        three: Color(FrostedColor.frostedTomato3),
        four: Color(FrostedColor.frostedTomato4),
        five: Color(FrostedColor.frostedTomato5),
        six: Color(FrostedColor.frostedTomato6),
        seven: Color(FrostedColor.frostedTomato7),
        eight: Color(FrostedColor.frostedTomato8),
        nine: Color(FrostedColor.frostedTomato9),
        contrastNine: Color(FrostedColor.frostedTomato9contrast),
        ten: Color(FrostedColor.frostedTomato10),
        eleven: Color(FrostedColor.frostedTomato11),
        twelve: Color(FrostedColor.frostedTomato12),
        A1: Color(FrostedColor.frostedTomatoA1),
        A2: Color(FrostedColor.frostedTomatoA2),
        A3: Color(FrostedColor.frostedTomatoA3),
        A4: Color(FrostedColor.frostedTomatoA4),
        A5: Color(FrostedColor.frostedTomatoA5),
        A6: Color(FrostedColor.frostedTomatoA6),
        A7: Color(FrostedColor.frostedTomatoA7),
        A8: Color(FrostedColor.frostedTomatoA8),
        A9: Color(FrostedColor.frostedTomatoA9),
        A10: Color(FrostedColor.frostedTomatoA10),
        A11: Color(FrostedColor.frostedTomatoA11),
        A12: Color(FrostedColor.frostedTomatoA12)
    )

    static let violet = FrostedTint(
        one: Color(FrostedColor.frostedViolet1),
        two: Color(FrostedColor.frostedViolet2),
        three: Color(FrostedColor.frostedViolet3),
        four: Color(FrostedColor.frostedViolet4),
        five: Color(FrostedColor.frostedViolet5),
        six: Color(FrostedColor.frostedViolet6),
        seven: Color(FrostedColor.frostedViolet7),
        eight: Color(FrostedColor.frostedViolet8),
        nine: Color(FrostedColor.frostedViolet9),
        contrastNine: Color(FrostedColor.frostedViolet9contrast),
        ten: Color(FrostedColor.frostedViolet10),
        eleven: Color(FrostedColor.frostedViolet11),
        twelve: Color(FrostedColor.frostedViolet12),
        A1: Color(FrostedColor.frostedVioletA1),
        A2: Color(FrostedColor.frostedVioletA2),
        A3: Color(FrostedColor.frostedVioletA3),
        A4: Color(FrostedColor.frostedVioletA4),
        A5: Color(FrostedColor.frostedVioletA5),
        A6: Color(FrostedColor.frostedVioletA6),
        A7: Color(FrostedColor.frostedVioletA7),
        A8: Color(FrostedColor.frostedVioletA8),
        A9: Color(FrostedColor.frostedVioletA9),
        A10: Color(FrostedColor.frostedVioletA10),
        A11: Color(FrostedColor.frostedVioletA11),
        A12: Color(FrostedColor.frostedVioletA12)
    )

    static let yellow = FrostedTint(
        one: Color(FrostedColor.frostedYellow1),
        two: Color(FrostedColor.frostedYellow2),
        three: Color(FrostedColor.frostedYellow3),
        four: Color(FrostedColor.frostedYellow4),
        five: Color(FrostedColor.frostedYellow5),
        six: Color(FrostedColor.frostedYellow6),
        seven: Color(FrostedColor.frostedYellow7),
        eight: Color(FrostedColor.frostedYellow8),
        nine: Color(FrostedColor.frostedYellow9),
        contrastNine: Color(FrostedColor.frostedYellow9contrast),
        ten: Color(FrostedColor.frostedYellow10),
        eleven: Color(FrostedColor.frostedYellow11),
        twelve: Color(FrostedColor.frostedYellow12),
        A1: Color(FrostedColor.frostedYellowA1),
        A2: Color(FrostedColor.frostedYellowA2),
        A3: Color(FrostedColor.frostedYellowA3),
        A4: Color(FrostedColor.frostedYellowA4),
        A5: Color(FrostedColor.frostedYellowA5),
        A6: Color(FrostedColor.frostedYellowA6),
        A7: Color(FrostedColor.frostedYellowA7),
        A8: Color(FrostedColor.frostedYellowA8),
        A9: Color(FrostedColor.frostedYellowA9),
        A10: Color(FrostedColor.frostedYellowA10),
        A11: Color(FrostedColor.frostedYellowA11),
        A12: Color(FrostedColor.frostedYellowA12)
    )
}
