on:
  workflow_dispatch:
  push:
    branches:
      - pull-icons

name: Generate Frosted Icons from Figma

concurrency:
  group: 'generate-icons'
  cancel-in-progress: false

jobs:
  generate-icons:
    name: Generate icons from Figma and commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          path: swift-repo

      - name: Clone frosted-ui repo
        uses: actions/checkout@v4
        with:
          repository: whopio/frosted-ui
          token: ${{ secrets.GITHUB_TOKEN }}
          path: frosted-ui

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          check-latest: true

      - name: Install dependencies
        run: pnpm i
        working-directory: ./frosted-ui

      - name: Generate icons from Figma
        run: pnpm generate-src
        working-directory: ./frosted-ui/packages/frosted-ui-icons
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}

      - name: Process icons into xcassets
        run: bash ./swift-repo/bin/generate_frosted_icons.sh ./frosted-ui/packages/frosted-ui-icons/frosted-ui-icons.zip

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update icons from Figma"
          file_pattern: "Sources/FrostedUI/Resources/Icons.xcassets/** Sources/FrostedUI/Icons/**"
          repository: ./swift-repo
